### ISSUE TITLE
how to visualize like the paper did

### ISSUE THREAD

**Issue by Nick32625** [Sina-Baharlou/Depth-VRD#3]
Cannot find the visualize code in this repository, can you upload the visualize code which create the picture in the paper? thank u very much.

**Comment by Sina-Baharlou** [comment]
Thank you for your interest in our code. Please note that the qualitative images in our paper are created with a separate tool for visualizing scene graphs and knowledge graphs. Currently, the code is not ready for release, but it will be soon uploaded in a separate repository. 

In the meantime, You can use the visualization code provided by [Neural-Motifs](https://github.com/rowanz/neural-motifs) repository which is similar to ours.
